// ─── Assessment Questions ─────────────────────────────────────────────────────
export const QUESTIONS = [
    { id: "education", text: "What is your current education level and field of study? (e.g., 12th Science PCM, B.Tech CSE 2nd year, MBA Finance, BA English graduate, Diploma in Mechanical)", placeholder: "I am currently studying / have completed...", icon: "🎓" },
    { id: "interests", text: "What subjects, activities, or topics genuinely excite you? Think about what you'd do even if you weren't paid. (e.g., coding, teaching, debating, designing, researching, writing, sports, music, social work)", placeholder: "I'm genuinely passionate about...", icon: "✦" },
    { id: "skills", text: "What are your strongest soft skills? What do friends, family, or teachers often praise you for? (e.g., leadership, communication, problem-solving, creativity, empathy, organisation)", placeholder: "People often say I'm good at...", icon: "◈" },
    { id: "technical_skills", text: "What technical or domain-specific skills do you have? (e.g., Python, Excel, Photoshop, video editing, lab work, accounting, public speaking, CAD, writing, data analysis)", placeholder: "My technical skills include...", icon: "⚙" },
    { id: "work_style", text: "How do you prefer to work? Describe your ideal work environment. (Solo vs team, creative vs structured, fast-paced vs methodical, fieldwork vs desk job, fixed hours vs flexible)", placeholder: "I work best when...", icon: "◉" },
    { id: "people_data_systems", text: "Do you enjoy working more with people (teaching, counselling, sales), data/numbers (analysis, research, finance), or building things/systems (engineering, coding, design)?", placeholder: "I enjoy working most with...", icon: "◎" },
    { id: "values", text: "What matters most to you in a career? Rank or describe your top priorities. (Job security, high salary, work-life balance, social impact, creativity, government job stability, entrepreneurship, foreign opportunities)", placeholder: "What I value most in my career is...", icon: "◆" },
    { id: "location", text: "Where would you prefer to work? (Metro cities like Mumbai/Delhi/Bangalore, Tier-2 cities like Jaipur/Pune/Lucknow, your hometown, remote/WFH, open to anywhere, abroad)", placeholder: "I'd prefer to work in...", icon: "📍" },
    { id: "sector_pref", text: "Which sector appeals to you most? (Government/PSU, private corporate, startups, freelancing/self-employed, NGO/social sector, academia/research, or open to any)", placeholder: "I'm most drawn towards...", icon: "🏢" },
    { id: "budget_timeline", text: "How much time and money are you willing to invest in upskilling or further education? (e.g., 6 months self-study, 2-year master's degree, online courses only, ready for competitive exam prep for 1-2 years)", placeholder: "I can invest approximately...", icon: "⏳" },
    { id: "weaknesses", text: "What are your weaknesses or areas you want to improve? Be honest — it helps us guide you better. (e.g., public speaking, maths, time management, confidence, English fluency, technical skills)", placeholder: "I struggle with...", icon: "◇" },
    { id: "aspirations", text: "Where do you see yourself in 5–10 years? What does your dream career or life look like? (e.g., leading a tech team, running my own business, working in the IAS, settled abroad, teaching at a university)", placeholder: "In 5-10 years, I see myself...", icon: "🚀" },
];
